# build stage
FROM node:14-alpine as build-stage
WORKDIR /app
COPY package*.json  package-lock.json ./

RUN apk add --update python3 make g++\
   && rm -rf /var/cache/apk/*
RUN npm install --save node-fetch@2
RUN npm install
COPY . .
RUN npm run build:local

# production stage
FROM nginx:stable-alpine as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]

